Added channel for sas mode status on 36
LRTNZ/KerbalSimpitRevamped pull request #19
Opened 2020-12-02 22:49 UTC by TheDicko

2020-12-03 21:30 UTC, PBechon reviewed
I think the code can be simplified before merging

2020-12-03 21:30 UTC, PBechon commented on KerbalSimpit/Providers/AxisControl.cs
> +                }
Why not use `SASModeSend = currentSASMode` instead of testing each value ?

2020-12-03 21:30 UTC, PBechon commented on KerbalSimpit/Providers/AxisControl.cs
> +            if (currentSASMode != prevSASMode)
Shouldn't we send this information at each tick instead of when it changes only ?

2020-12-04 02:31 UTC, LRTNZ requested changes
@TheDicko could you please take a look into the AutopilotMode enum, and see if there is a more concise way of doing this?
Also the debug log output stuff as well.

2020-12-04 02:31 UTC, LRTNZ commented on KerbalSimpit/Providers/AxisControl.cs
> +                }
I am not sure what the type of value that the AutopilotMode enum points to is. If it does not have a value like an int/byte in it, I would say a switch statement would be better here @TheDicko

2020-12-04 02:31 UTC, LRTNZ commented on KerbalSimpit/Providers/AxisControl.cs
> +            if (currentSASMode != prevSASMode)
Currently Actions only sends info when something has been changed: https://github.com/LRTNZ/KerbalSimpitRevamped/blob/e03360dc62f0ff65eb327378b03a5e4c75e5fb5a/KerbalSimpit/Providers/Actions.cs#L90-L100

2020-12-04 02:31 UTC, LRTNZ commented on KerbalSimpit/Providers/AxisControl.cs
> +                    Debug.Log(String.Format("KerbalSimpit: SAS Mode is Prograde"));
Can you please look at making a small helper method that can be called to print the current SAS mode, when the mod is in verbose mode?
As currently, you are repeating the same string an awful lot, when the only difference is the name of the SAS mode. Ideally the method should just take in a string parameter of the name of the mode, and contain the "KerbalSimpit: SAS Mode is " preamble in it.

2021-04-16 20:01 UTC, PBechon commented
Closing this PR as #53 as been merged and it implements this message.

2021-04-16 20:01 UTC, closed without merging