Add support for the Timewarp message.
LRTNZ/KerbalSimpitRevamped pull request #28
Opened 2020-12-19 22:01 UTC by PBechon

The Warp to next SOI is still to be implemented, all the others messages are implemented and tested.

2020-12-22 06:39 UTC, LRTNZ requested changes
Could you please take a look at all of these areas, and submit the changes/technical reasoning to not change them.

2020-12-22 07:25 UTC, PBechon commented on KerbalSimpit/KerbalSimpitPackets.cs
> +    }
I will rename as the rest of the code use this style of constant definition

2020-12-22 07:26 UTC, PBechon commented on KerbalSimpit/Providers/WarpControl.cs
> +                    break;
This is the job of the setWarpRate function to look up the index to use based on the desired rate (see line 46 and 65).

2020-12-22 07:28 UTC, PBechon commented on KerbalSimpit/Providers/WarpControl.cs
> +                    break;
Setting a timewarp of x1 works both for physical and non physical. Same with timewarp up and down, they work on both cases.

2020-12-22 08:31 UTC, LRTNZ commented on KerbalSimpit/Providers/WarpControl.cs
> +                    break;
> 
> 
> This is the job of the setWarpRate function to look up the index to use based on the desired rate (see line 46 and 65).

My point still applies - you are manually encoding the timewarp rate into the code. Then your code looks for the index of that value you have programmed, to pass that index to the SetRate method, which then uses the index to get the value you just got the index for.  
What if I make a mod that changes all of the timewarp speeds to be faster - which can be done, as the array of warp rates is not constant. Then when this code goes to look for a specific value in the array, to get it's index, it will not find any of my changed values.

I would suggest changing what you have to be timewarp0, timewarp1, etc - then just pass the index directly into your code, without doing the reverse lookup. I am happy to look at making these changes myself, if that would be easier.

2020-12-22 08:33 UTC, LRTNZ commented on KerbalSimpit/Providers/WarpControl.cs
> +                    break;
> 
> 
> Setting a timewarp of x1 works both for physical and non physical. Same with timewarp up and down, they work on both cases.

But if timewarp physical has been broken out into a separately controllable thing, it would make sense to be able to set a physical timewarp of 1.

2020-12-22 08:34 UTC, LRTNZ commented on KerbalSimpit/KerbalSimpitPackets.cs
> +    }
Thanks!

2020-12-22 20:37 UTC, PBechon commented
I added the Warp to SOI message and made the first requested change

2021-01-05 04:24 UTC, LRTNZ approved these changes
I will look into tweaking the parts I would like to see changed myself, as what I am after is a bit hard to explain. Thanks for the core work!

2021-01-05 04:31 UTC, merged